[package]
name = "sortedlist"
version = "0.1.0"
authors = ["frederic wagner <frederic.wagner@univ-grenoble-alpes.fr>"]
edition = "2018"

[dev-dependencies]
criterion="*"
rand="*"

[[bench]]
name = "insertions"
harness = false
